/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.wamp (standalone).
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_TESTCASES_EXAMPLE77_Example_Interface_WAMP_STRUCTS_SUPPORT_HPP_
#define V0_TESTCASES_EXAMPLE77_Example_Interface_WAMP_STRUCTS_SUPPORT_HPP_

#include <v0/testcases/example77/ExampleInterface.hpp>
#include <msgpack.hpp>

namespace msgpack {
MSGPACK_API_VERSION_NAMESPACE(MSGPACK_DEFAULT_API_NS) {
namespace adaptor {

template<>
struct convert<::v0::testcases::example77::ExampleInterface::Summands> {
	msgpack::object const& operator()(msgpack::object const& o, ::v0::testcases::example77::ExampleInterface::Summands& v) const {
		if (o.type != msgpack::type::ARRAY) throw msgpack::type_error();
		if (o.via.array.size != 2) throw msgpack::type_error();
		v = ::v0::testcases::example77::ExampleInterface::Summands (
			o.via.array.ptr[0].as<uint64_t>(),
			o.via.array.ptr[1].as<uint64_t>()
        );
		return o;
	}
};

template<>
struct convert<::v0::testcases::example77::ExampleInterface::Params> {
	msgpack::object const& operator()(msgpack::object const& o, ::v0::testcases::example77::ExampleInterface::Params& v) const {
		if (o.type != msgpack::type::ARRAY) throw msgpack::type_error();
		if (o.via.array.size != 2) throw msgpack::type_error();
		v = ::v0::testcases::example77::ExampleInterface::Params (
			o.via.array.ptr[0].as<::v0::testcases::example77::ExampleInterface::Summands>(),
			o.via.array.ptr[1].as<uint64_t>()
        );
		return o;
	}
};

template<>
struct convert<::v0::testcases::example77::ExampleInterface::SumDiff> {
	msgpack::object const& operator()(msgpack::object const& o, ::v0::testcases::example77::ExampleInterface::SumDiff& v) const {
		if (o.type != msgpack::type::ARRAY) throw msgpack::type_error();
		if (o.via.array.size != 2) throw msgpack::type_error();
		v = ::v0::testcases::example77::ExampleInterface::SumDiff (
			o.via.array.ptr[0].as<uint64_t>(),
			o.via.array.ptr[1].as<uint64_t>()
        );
		return o;
	}
};

} // namespace adaptor
} // MSGPACK_API_VERSION_NAMESPACE(MSGPACK_DEFAULT_API_NS)
} // namespace msgpack

#endif // V0_TESTCASES_EXAMPLE77_Example_Interface_WAMP_STRUCTS_SUPPORT_HPP_

