/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.wamp (standalone).
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/

#include "v0/testcases/example32/ExampleInterfaceWampStructsSupport.hpp"

namespace v0 {
namespace testcases {
namespace example32 {

MyStruct_internal transformMyStruct(const ExampleInterface::MyStruct &inst)
{
	return inst.values_;
}

ExampleInterface::MyStruct transformMyStruct(const MyStruct_internal &inst_internal)
{
	// TODO: Check if it is ok to return a struct on the stack. 
	ExampleInterface::MyStruct inst;
	inst.values_ = inst_internal;
	return inst;
}


} // namespace example32
} // namespace testcases
} // namespace v0
