/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.wamp (standalone).
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/

#ifndef V0_TESTCASES_EXAMPLE11_Example_Interface_WAMP_DEPLOYMENT_HPP_
#define V0_TESTCASES_EXAMPLE11_Example_Interface_WAMP_DEPLOYMENT_HPP_



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif
//#include <CommonAPI/Wamp/WampDeployment.hpp>
#undef COMMONAPI_INTERNAL_COMPILATION

namespace v0 {
namespace testcases {
namespace example11 {
namespace ExampleInterface_ {


} // namespace ExampleInterface_
} // namespace example11
} // namespace testcases
} // namespace v0

#endif // V0_TESTCASES_EXAMPLE11_Example_Interface_WAMP_DEPLOYMENT_HPP_

