/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.wamp (standalone).
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_TESTCASES_EXAMPLE10_Example_Interface_WAMP_STRUCTS_SUPPORT_HPP_
#define V0_TESTCASES_EXAMPLE10_Example_Interface_WAMP_STRUCTS_SUPPORT_HPP_

#include <v0/testcases/example10/ExampleInterface.hpp>

namespace v0 {
namespace testcases {
namespace example10 {

} // namespace example10
} // namespace testcases
} // namespace v0

#endif // V0_TESTCASES_EXAMPLE10_Example_Interface_WAMP_STRUCTS_SUPPORT_HPP_

