/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.wamp (standalone).
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef TESTCASES_EXAMPLE77_Example_Interface_WAMP_STRUCTS_SUPPORT_HPP_
#define TESTCASES_EXAMPLE77_Example_Interface_WAMP_STRUCTS_SUPPORT_HPP_

#include <testcases/example77/ExampleInterface.hpp>

namespace testcases {
namespace example77 {

typedef std::tuple<uint64_t, uint64_t> Summands_internal;
extern Summands_internal transformSummands(const ExampleInterface::Summands &summands);
extern ExampleInterface::Summands transformSummands(const Summands_internal &summands_internal);

typedef std::tuple<Summands_internal, uint64_t> Params_internal;
extern Params_internal transformParams(const ExampleInterface::Params &params);
extern ExampleInterface::Params transformParams(const Params_internal &params_internal);

typedef std::tuple<uint64_t, uint64_t> SumDiff_internal;
extern SumDiff_internal transformSumDiff(const ExampleInterface::SumDiff &sumDiff);
extern ExampleInterface::SumDiff transformSumDiff(const SumDiff_internal &sumDiff_internal);

} // namespace example77
} // namespace testcases

#endif // TESTCASES_EXAMPLE77_Example_Interface_WAMP_STRUCTS_SUPPORT_HPP_
